const imageFilenames = [
"artistic-boudoir-posing-at-mirror.jpg",
"artistic-boudoir-standing-in-shadows.jpg",
"artistic-boudoir-touching-at-window.jpg",
"artistic-gaze-posing-on-chair.jpg",
"artistic-gaze-sitting-at-bed.jpg",
"artistic-gaze-stretching-on-floor.jpg",
"artistic-light-reflecting-in-bedroom.jpg",
"artistic-light-sitting-in-bedroom.jpg",
"artistic-lingerie-gazing-at-mirror.jpg",
"artistic-lingerie-gazing-on-floor.jpg",
"artistic-lingerie-posing-at-doorway.jpg",
"artistic-lingerie-posing-at-mirror.jpg",
"artistic-lingerie-posing-in-bedroom.jpg",
"artistic-lingerie-reflecting-on-chair.jpg",
"artistic-look-gazing-at-window.jpg",
"artistic-look-leaning-in-bedroom.jpg",
"artistic-look-posing-on-floor.jpg",
"artistic-look-reclining-at-doorway.jpg",
"artistic-look-reclining-at-window.jpg",
"artistic-look-reflecting-in-hallway.jpg",
"artistic-mood-reclining-on-couch.jpg",
"artistic-mood-reflecting-on-chair.jpg",
"artistic-mood-resting-in-shadows.jpg",
"artistic-mood-resting-on-couch.jpg",
"lesbian-pose-posing-at-bed.jpg",
"lesbian-pose-reclining-at-doorway.jpg",
"lesbian-shadow-posing-in-hallway.jpg",
"lesbian-shadow-resting-on-floor.jpg",
"lesbian-shadow-stretching-at-bed.jpg",
"lesbian-shape-gazing-on-chair.jpg",
"lesbian-shape-reflecting-at-bed.jpg",
"lesbian-shape-sitting-at-doorway.jpg",
"lesbian-shape-stretching-at-doorway.jpg",
"lesbian-shape-stretching-on-chair.jpg",
"lesbian-silhouette-leaning-in-hallway.jpg",
"lesbian-silhouette-resting-at-doorway.jpg",
"lesbian-silhouette-resting-at-window.jpg",
"lesbian-silhouette-touching-in-shadows.jpg",
"close-up-boudoir-gazing-on-chair.jpg",
"close-up-boudoir-leaning-in-hallway.jpg",
"close-up-boudoir-reclining-at-mirror.jpg",
"close-up-boudoir-reflecting-at-mirror.jpg",
"close-up-gaze-gazing-on-chair.jpg",
"close-up-gaze-posing-at-mirror.jpg",
"close-up-gaze-standing-in-shadows.jpg",
"close-up-light-gazing-on-floor.jpg",
"close-up-light-reflecting-in-hallway.jpg",
"close-up-light-reflecting-on-couch.jpg",
"close-up-light-standing-in-hallway.jpg",
"delicate-lingerie-reclining-on-chair.jpg",
"delicate-lingerie-resting-on-floor.jpg",
"delicate-lingerie-sitting-at-mirror.jpg",
"delicate-lingerie-touching-at-doorway.jpg",
"delicate-lingerie-touching-in-hallway.jpg",
"delicate-lingerie-touching-on-chair.jpg",
"delicate-look-gazing-at-doorway.jpg",
"delicate-look-gazing-on-couch.jpg",
"delicate-look-leaning-at-mirror.jpg",
"delicate-look-posing-at-mirror.jpg",
"sexy-look-resting-in-bedroom.jpg",
"sexy-look-touching-at-doorway.jpg",
"sexy-mood-leaning-in-hallway.jpg",
"sexy-mood-reflecting-at-bed.jpg",
"sexy-mood-reflecting-at-mirror.jpg",
"sexy-mood-stretching-in-shadows.jpg",
"sexy-mood-touching-in-shadows.jpg",
"sexy-pose-reclining-at-doorway.jpg",
"nude-pose-reclining-at-mirror.jpg",
"nude-pose-reflecting-at-window.jpg",
"nude-pose-sitting-on-couch.jpg",
"nude-pose-standing-on-floor.jpg",
"nude-pose-touching-on-couch.jpg",
"nude-shadow-gazing-in-shadows.jpg",
"nude-shadow-gazing-on-couch.jpg",
"nude-shadow-sitting-in-bedroom.jpg",
"nude-shadow-standing-on-chair.jpg",
"nude-shadow-touching-at-doorway.jpg",
"delicate-shape-reclining-at-bed.jpg",
"delicate-shape-reflecting-in-hallway.jpg",
"delicate-shape-resting-at-bed.jpg",
"delicate-shape-standing-on-couch.jpg",
"delicate-silhouette-gazing-in-bedroom.jpg",
"delicate-silhouette-gazing-on-couch.jpg",
"delicate-silhouette-gazing-on-floor.jpg",
"delicate-silhouette-posing-in-bedroom.jpg",
"delicate-silhouette-posing-on-couch.jpg",
"delicate-silhouette-reclining-in-hallway.jpg",
"delicate-silhouette-reclining-on-chair.jpg",
"delicate-silhouette-resting-on-chair.jpg",
"delicate-silhouette-standing-at-doorway.jpg",
"delicate-silhouette-stretching-at-bed.jpg",
"delicate-silhouette-touching-in-bedroom.jpg",
"dreamy-boudoir-gazing-at-window.jpg",
"dreamy-boudoir-leaning-at-window.jpg",
"dreamy-gaze-reclining-at-mirror.jpg",
"dreamy-gaze-reflecting-at-window.jpg",
"dreamy-gaze-resting-on-couch.jpg",
"dreamy-light-gazing-at-window.jpg",
"dreamy-light-reflecting-in-shadows.jpg",
"dreamy-light-resting-on-floor.jpg",
"dreamy-light-standing-in-hallway.jpg",
"dreamy-light-stretching-at-bed.jpg",
"dreamy-lingerie-reflecting-in-hallway.jpg",
"dreamy-lingerie-touching-on-chair.jpg",
"dreamy-lingerie-touching-on-couch.jpg",
"dreamy-look-gazing-on-couch.jpg",
"dreamy-look-touching-on-floor.jpg",
"dreamy-mood-leaning-at-bed.jpg",
"dreamy-mood-stretching-at-bed.jpg",
"dreamy-mood-stretching-in-hallway.jpg",
"dreamy-mood-touching-in-shadows.jpg",
"dreamy-pose-gazing-at-window.jpg",
"dreamy-pose-leaning-at-doorway.jpg",
"dreamy-pose-reflecting-on-floor.jpg",
"dreamy-shadow-posing-on-chair.jpg",
"dreamy-shadow-resting-in-shadows.jpg",
"dreamy-shadow-sitting-on-floor.jpg",
"dreamy-shadow-stretching-at-window.jpg",
"dreamy-shadow-stretching-in-bedroom.jpg",
"dreamy-shadow-stretching-on-couch.jpg",
"dreamy-shape-reclining-in-shadows.jpg",
"dreamy-shape-reflecting-at-bed.jpg",
"dreamy-shape-sitting-in-shadows.jpg",
"dreamy-silhouette-sitting-in-bedroom.jpg",
"dreamy-silhouette-sitting-on-chair.jpg",
"dreamy-silhouette-standing-on-couch.jpg",
"elegant-boudoir-leaning-at-doorway.jpg",
"elegant-boudoir-leaning-in-shadows.jpg",
"elegant-boudoir-touching-in-hallway.jpg",
"elegant-gaze-resting-in-hallway.jpg",
"elegant-light-standing-at-forest.jpg",
"elegant-lingerie-gazing-in-dark.jpg",
"elegant-lingerie-posing-at-forest.jpg",
"elegant-lingerie-sitting-on-chair.jpg",
"elegant-lingerie-touching-at-doorway.jpg",
"elegant-lingerie-touching-at-mirror.jpg",
"elegant-look-gazing-in-hallway.jpg",
"elegant-look-gazing-on-couch.jpg",
"elegant-look-reclining-in-shadows.jpg",
"elegant-look-reflecting-in-bedroom.jpg",
"elegant-look-touching-at-bed.jpg",
"elegant-mood-leaning-in-shadows.jpg",
"elegant-mood-reclining-at-doorway.jpg",
"elegant-mood-reflecting-in-hallway.jpg",
"elegant-mood-resting-at-window.jpg",
"elegant-mood-standing-at-bed.jpg",
"elegant-pose-gazing-at-bed.jpg",
"elegant-pose-leaning-on-water.jpg",
"elegant-pose-reclining-on-sea.jpg",
"elegant-pose-reflecting-on-beach.jpg",
"elegant-pose-stretching-at-doorway.jpg",
"elegant-pose-touching-on-couch.jpg",
"elegant-shadow-gazing-in-bedroom.jpg",
"elegant-shadow-gazing-in-shadows.jpg",
"elegant-shadow-reflecting-in-hallway.jpg",
"elegant-shadow-resting-at-garden.jpg",
"elegant-shadow-sitting-on-floor.jpg",
"elegant-shadow-stretching-in-shadows.jpg",
"elegant-shadow-touching-at-window.jpg",
"elegant-shape-resting-in-bedroom.jpg",
"elegant-shape-touching-at-doorway.jpg",
"elegant-silhouette-standing-at-doorway.jpg",
"gentle-boudoir-leaning-in-shadows.jpg",
"gentle-boudoir-posing-on-chair.jpg",
"gentle-boudoir-sitting-on-floor.jpg",
"gentle-boudoir-stretching-on-couch.jpg",
"gentle-gaze-posing-at-doorway.jpg",
"gentle-gaze-reclining-at-doorway.jpg",
"gentle-gaze-resting-on-chair.jpg",
"gentle-gaze-stretching-in-shadows.jpg",
"gentle-gaze-touching-in-shadows.jpg",
"gentle-light-reclining-at-window.jpg",
"gentle-light-reflecting-at-window.jpg",
"gentle-light-reflecting-in-bedroom.jpg",
"gentle-light-reflecting-in-shadows.jpg",
"gentle-lingerie-gazing-on-chair.jpg",
"gentle-lingerie-leaning-on-couch.jpg",
"gentle-lingerie-standing-in-hallway.jpg",
"gentle-lingerie-stretching-at-mirror.jpg",
"gentle-look-gazing-at-doorway.jpg",
"gentle-look-leaning-in-bedroom.jpg",
"gentle-look-reflecting-at-doorway.jpg",
"gentle-look-standing-on-chair.jpg",
"gentle-mood-gazing-in-bedroom.jpg",
"gentle-mood-leaning-on-chair.jpg",
"gentle-mood-posing-on-couch.jpg",
"gentle-mood-reclining-at-mirror.jpg",
"gentle-mood-resting-on-couch.jpg",
"gentle-mood-sitting-in-shadows.jpg",
"gentle-mood-stretching-on-couch.jpg",
"gentle-pose-standing-on-floor.jpg",
"gentle-pose-stretching-at-window.jpg",
"gentle-pose-touching-in-hallway.jpg",
"gentle-pose-touching-on-chair.jpg",
"gentle-shadow-reclining-on-floor.jpg",
"gentle-shadow-resting-on-chair.jpg",
"gentle-shape-gazing-at-mirror.jpg",
"gentle-shape-reclining-on-chair.jpg",
"gentle-shape-resting-on-chair.jpg",
"gentle-shape-stretching-in-bedroom.jpg",
"gentle-silhouette-leaning-at-window.jpg",
"gentle-silhouette-posing-at-mirror.jpg",
"gentle-silhouette-reclining-in-bedroom.jpg",
"gentle-silhouette-reflecting-at-bed.jpg",
"gentle-silhouette-resting-on-chair.jpg",
"gentle-silhouette-sitting-in-bedroom.jpg",
"gentle-silhouette-standing-at-bed.jpg",
"gentle-silhouette-touching-at-doorway.jpg",
"graceful-boudoir-gazing-at-bed.jpg",
"graceful-boudoir-gazing-in-bedroom.jpg",
"graceful-boudoir-touching-in-hallway.jpg",
"graceful-gaze-resting-on-floor.jpg",
"graceful-gaze-stretching-on-chair.jpg",
"graceful-gaze-touching-at-doorway.jpg",
"graceful-light-gazing-at-window.jpg",
"graceful-light-gazing-in-dark.jpg",
"graceful-light-reclining-at-doorway.jpg",
"graceful-lingerie-gazing-in-bedroom.jpg",
"graceful-lingerie-posing-on-couch.jpg",
"graceful-lingerie-reclining-at-bed.jpg",
"graceful-lingerie-reclining-at-mirror.jpg",
"graceful-lingerie-reclining-in-bedroom.jpg",
"graceful-lingerie-reflecting-at-bed.jpg",
"graceful-lingerie-reflecting-in-hallway.jpg",
"graceful-lingerie-reflecting-in-shadows.jpg",
"graceful-lingerie-sitting-on-chair.jpg",
"graceful-look-gazing-at-window.jpg",
"graceful-look-reclining-on-floor.jpg",
"graceful-mood-gazing-at-bed.jpg",
"graceful-mood-posing-on-chair.jpg",
"graceful-mood-reclining-on-floor.jpg",
"graceful-pose-sitting-in-shadows.jpg",
"graceful-shadow-gazing-in-bedroom.jpg",
"graceful-shadow-touching-on-couch.jpg",
"graceful-shape-reclining-in-hallway.jpg",
"graceful-shape-resting-in-bedroom.jpg",
"graceful-shape-touching-at-bed.jpg",
"graceful-shape-touching-at-window.jpg",
"graceful-shape-touching-in-shadows.jpg",
"graceful-silhouette-reclining-on-couch.jpg",
"graceful-silhouette-resting-in-shadows.jpg",
"graceful-silhouette-touching-at-bed.jpg",
"graceful-silhouette-touching-at-doorway.jpg",
"graceful-silhouette-touching-on-chair.jpg",
"intimate-boudoir-posing-in-shadows.jpg",
"intimate-boudoir-resting-in-bedroom.jpg",
"intimate-gaze-leaning-on-couch.jpg",
"intimate-gaze-posing-in-hallway.jpg",
"intimate-gaze-sitting-at-doorway.jpg",
"intimate-light-posing-at-window.jpg",
"intimate-lesbian-touching-at-bed.jpg",
"intimate-lesbian-touching-on-couch.jpg",
"intimate-lesbian-posing-on-couch.jpg",
"intimate-lesbian-resting-on-couch.jpg",
"intimate-lesbian-sitting-in-shadows.jpg",
"intimate-lingerie-touching-at-window.jpg",
"intimate-lesbian-gazing-in-shadows.jpg",
"intimate-lesbian-posing-on-floor.jpg",
"intimate-lesbian-stretching-at-doorway.jpg",
"intimate-lesbian-touching-at-mirror.jpg",
"intimate-lesbian-posing-at-mirror.jpg",
"intimate-mood-reflecting-at-window.jpg",
"intimate-mood-reflecting-on-chair.jpg",
"intimate-pose-leaning-in-bedroom.jpg",
"intimate-pose-reclining-at-doorway.jpg",
"intimate-pose-standing-at-mirror.jpg",
"intimate-pose-standing-in-shadows.jpg",
"intimate-pose-touching-in-shadows.jpg",
"intimate-shadow-reflecting-at-doorway.jpg",
"intimate-shadow-reflecting-in-bedroom.jpg",
"intimate-shadow-reflecting-on-couch.jpg",
"intimate-shadow-touching-on-chair.jpg",
"intimate-shape-stretching-in-bedroom.jpg",
"intimate-shape-touching-at-window.jpg",
"intimate-silhouette-leaning-in-hallway.jpg",
"intimate-silhouette-posing-in-hallway.jpg",
"intimate-silhouette-reflecting-on-chair.jpg",
"intimate-silhouette-touching-on-couch.jpg",
"moody-boudoir-gazing-on-chair.jpg",
"moody-boudoir-posing-at-bed.jpg",
"moody-boudoir-posing-in-bedroom.jpg",
"moody-boudoir-posing-on-floor.jpg",
"moody-boudoir-reclining-on-chair.jpg",
"moody-boudoir-reclining-on-couch.jpg",
"moody-boudoir-reflecting-on-floor.jpg",
"moody-boudoir-sitting-at-doorway.jpg",
"moody-nude-gazing-in-shadows.jpg",
"moody-nude-leaning-on-floor.jpg",
"moody-nude-posing-in-bedroom.jpg",
"moody-nude-posing-on-bed.jpg",
"moody-nude-posing-on-floor.jpg",
"moody-nude-resting-in-shadows.jpg",
"moody-nude-sitting-in-bedroom.jpg",
"moody-nude-sitting-in-shadows.jpg",
"moody-lingerie-gazing-at-window.jpg",
"moody-lingerie-reclining-on-floor.jpg",
"moody-lingerie-reflecting-at-window.jpg",
"moody-lingerie-sitting-on-floor.jpg",
"moody-look-reclining-at-mirror.jpg",
"moody-look-reflecting-in-hallway.jpg",
"moody-look-stretching-in-shadows.jpg",
"moody-bdsm-posing-in-hallway.jpg",
"moody-bdsm-resting-in-bedroom.jpg",
"moody-bdsm-stretching-in-hallway.jpg",
"moody-bdsm-stretching-on-floor.jpg",
"moody-bdsm-posing-on-chair.jpg",
"moody-bdsm-stretching-at-window.jpg",
"moody-bdsm-touching-in-bedroom.jpg",
"moody-shadow-reclining-on-couch.jpg",
"moody-shadow-resting-on-couch.jpg",
"moody-shadow-stretching-at-window.jpg",
"moody-shape-gazing-at-bed.jpg",
"moody-shape-reflecting-at-mirror.jpg",
"moody-shape-resting-at-mirror.jpg",
"moody-shape-sitting-at-mirror.jpg",
"moody-shape-sitting-at-window.jpg",
"moody-silhouette-touching-on-floor.jpg",
"sensual-boudoir-leaning-at-window.jpg",
"sensual-boudoir-reclining-on-couch.jpg",
"sensual-gaze-gazing-on-chair.jpg",
"sensual-gaze-leaning-at-bed.jpg",
"sensual-gaze-touching-in-shadows.jpg",
"sensual-women-leaning-at-doorway.jpg",
"sensual-women-leaning-in-shadows.jpg",
"sensual-women-stretching-on-floor.jpg",
"sensual-women-touching-at-doorway.jpg",
"erotic-lingerie-gazing-at-bed.jpg",
"erotic-lingerie-standing-at-mirror.jpg",
"erotic-lingerie-standing-in-hallway.jpg",
"erotic-lingerie-stretching-at-window.jpg",
"erotic-women-posing-in-shadows.jpg",
"erotic-women-reflecting-at-bed.jpg",
"erotic-women-resting-in-hallway.jpg",
"erotic-women-sitting-on-chair.jpg",
"erotic-women-sitting-on-couch.jpg",
"erotic-women-standing-at-bed.jpg",
"erotic-women-gazing-on-floor.jpg",
"erotic-women-reclining-on-couch.jpg",
"sensual-mood-sitting-at-bed.jpg",
"sensual-mood-sitting-on-chair.jpg",
"sensual-mood-stretching-in-hallway.jpg",
"sensual-mood-touching-in-hallway.jpg",
"sensual-mood-touching-on-floor.jpg",
"nsfw-pose-gazing-on-chair.jpg",
"nsfw-pose-leaning-in-bedroom.jpg",
"nsfw-pose-reflecting-at-bed.jpg",
"nsfw-bdsm-reclining-on-couch.jpg",
"nsfw-bdsm-resting-in-hallway.jpg",
"nsfw-bdsm-stretching-at-mirror.jpg",
"nsfw-shape-leaning-in-bedroom.jpg",
"sensual-shape-reclining-in-dark.jpg",
"sensual-shape-reflecting-at-mirror.jpg",
"sensual-shape-touching-in-shadows.jpg",
"sensual-shape-touching-on-couch.jpg",
"sensual-silhouette-reclining-at-beach.jpg",
"sensual-silhouette-sitting-at-beach.jpg",
"sensual-silhouette-sitting-in-hallway.jpg",
"sensual-silhouette-standing-in-hallway.jpg",
"soft-boudoir-reflecting-in-shadows.jpg",
"soft-gaze-gazing-on-floor.jpg",
"soft-gaze-reflecting-on-floor.jpg",
"soft-gaze-sitting-in-shadows.jpg",
"soft-gaze-stretching-at-doorway.jpg",
"soft-gaze-stretching-on-couch.jpg",
"soft-light-posing-in-shadows.jpg",
"soft-light-resting-in-hallway.jpg",
"soft-light-resting-in-shadows.jpg",
"soft-light-stretching-at-doorway.jpg",
"soft-lingerie-posing-in-hallway.jpg",
"soft-lingerie-posing-on-couch.jpg",
"soft-lingerie-reflecting-at-bed.jpg",
"soft-lingerie-resting-at-doorway.jpg",
"soft-lingerie-stretching-on-couch.jpg",
"soft-lingerie-touching-at-doorway.jpg",
"soft-lingerie-touching-on-floor.jpg",
"soft-look-gazing-on-floor.jpg",
"soft-look-leaning-in-hallway.jpg",
"soft-look-leaning-on-floor.jpg",
"soft-look-reflecting-on-chair.jpg",
"soft-look-touching-at-mirror.jpg",
"soft-mood-gazing-at-doorway.jpg",
"soft-mood-leaning-at-mirror.jpg",
"soft-mood-standing-at-window.jpg",
"soft-mood-standing-on-chair.jpg",
"soft-pose-leaning-at-window.jpg",
"soft-pose-reclining-at-bed.jpg",
"soft-pose-reclining-at-doorway.jpg",
"soft-pose-reclining-at-window.jpg",
"soft-pose-resting-at-mirror.jpg",
"soft-pose-standing-in-bedroom.jpg",
"soft-shadow-gazing-at-mirror.jpg",
"soft-shadow-reflecting-in-bedroom.jpg",
"soft-shadow-stretching-in-shadows.jpg",
"soft-shape-resting-in-shadows.jpg",
"soft-shape-sitting-in-bedroom.jpg",
"soft-shape-standing-at-bed.jpg",
"nudes-silhouette-leaning-in-hallway.jpg",
"nudes-silhouette-reflecting-on-floor.jpg",
"nudes-silhouette-sitting-at-bed.jpg",
"nudes-silhouette-standing-on-chair.jpg"
];

let currentIndex = -1;

function getNextIndex() {
  let nextIndex;
  do {
    nextIndex = Math.floor(Math.random() * imageFilenames.length);
  } while (nextIndex === currentIndex);
  currentIndex = nextIndex;
  return nextIndex;
}

function updateImage() {
  const imgElement = document.getElementById("slideshow-image");
  const nextIndex = getNextIndex();

  // Start fade-out & blur
  imgElement.style.opacity = 0;
  imgElement.style.filter = "blur(10px)";

  // Delay a bit to allow transition, then change image
  setTimeout(() => {
    imgElement.src = "images/" + imageFilenames[nextIndex];
  }, 500);
}

// When image is loaded, fade it in and remove blur
document.addEventListener("DOMContentLoaded", () => {
  const imgElement = document.getElementById("slideshow-image");

  // 초기 이미지 바로 설정 (빈 src 방지)
  imgElement.src = "images/" + imageFilenames[0];

  imgElement.addEventListener("load", () => {
    document.getElementById("spinner").style.display = "none";
    imgElement.style.opacity = 1;
    imgElement.style.filter = "blur(0px)";
  });

  updateImage();
  setInterval(updateImage, 6000); // 6 seconds
});

// Disable right-click
document.addEventListener("contextmenu", function (e) {
  e.preventDefault();
});

const shareBtn = document.getElementById("share-button");

shareBtn.addEventListener("click", async () => {
  if (navigator.share) {
    try {
      await navigator.share({
        title: document.title,
        url: window.location.href
      });
    } catch (err) {
      console.log("Share canceled or failed", err);
    }
  } else {
    alert("Sharing not supported on this device.");
  }
});

